# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rush01-Plan42-GPS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rush01-Plan42-GPS
  pod 'MapboxNavigation', '~> 0.22'

end
